kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.appName }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  defaultBackend:
    service:
      name: {{ .Values.frontendAppName }}
      port:
        number: 80
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /api/(.*)
        backend:
          service:
            name: {{ .Values.backendAppName }}
            port:
              number: 8000
  - http:
      paths:
      - pathType: Prefix
        path: /(.*)
        backend:
          service:
            name: {{ .Values.frontendAppName }}
            port:
              number: 80
