kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.backendAppName }}
  labels:
    app: {{ .Values.backendAppName }}
spec:
  selector:
    app: {{ .Values.backendAppName }}
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
