kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.backendAppName }}
  labels:
    app: {{ .Values.backendAppName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backendAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendAppName }}
    spec:
      containers:
        - name: backend
          image: {{ .Values.backendImage }}
          ports:
            - name: http
              containerPort: 80