kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.frontendUrl }}
  labels:
    app: {{ .Values.frontendAppName }}
spec:
  selector:
    app: {{ .Values.frontendAppName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
