kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.frontendAppName }}
  labels:
    app: {{ .Values.frontendAppName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.frontendAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontendAppName }}
    spec:
      containers:
        - name: nginx
          image:  {{ .Values.frontendImage }}
          ports:
            - containerPort: 80
              readinessProbe:
                httpGet:
                  scheme: HTTP
                  path: /
                  port: 80
