name: Deploy and Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  repository_dispatch:
    types: [frontend-test]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  deploy_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        with:
          config: kind-cluster-config.yaml
          cluster_name: default

      - run: helm install --wait --set providerUrl=${{ secrets.PROVIDER_URL }} --set usdcContractAddress=${{ secrets.USDC_CONTRACT_ADDRESS }} app-stack app-stack-chart
      - run: kubectl wait --namespace ingress-nginx --for=condition=ready pod --selector=app.kubernetes.io/component=controller --timeout=90s
      - run: curl localhost
      - run: curl localhost/api/status
      - run: docker run --name cypress-tests --add-host=host.docker.internal:host-gateway -e CYPRESS_BASE_URL="http://host.docker.internal" ${{ env.REGISTRY }}/dnch-chernov/wallet-info-tests:main

      - name: Job logs
        if: ${{ always() }}
        run: docker logs cypress-tests
